# -*- coding: utf-8 -*-
"""Base_dados_Netflix_09_02_(5).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MBlzSk7rnwxJc0fsoZ8lR9R_9tK5acaI

Observações sobre o dataset:
- O intervalo das datas de lançamento variam entre os anos de  1925 a 2021;
"""

#importando as bibliotecas de visualização:
import matplotlib.pyplot as plt
import seaborn as sns

import pandas as pd
import numpy as np

base_netflix = pd.read_csv('netflix_titles.csv')
base_netflix.head(10)

"""No primeiro contato com este conjunto de dados foi possível notar que temos 12 colunas no dataframe. E cada coluna tem o seguinte significado:

* show_id: Identificação única de cada linha da base de dados(PK)
* type: Categoria/classificação do que se trata o vídeo.
* title: Nome do vídeo em questão
* director: Nome do diretor do vídeo.
* cast: Nome do elenco que participa do vídeo.
* country: Países onde foi produzido o vídeo.
* data_added: data em que o vídeo foi adicionado a netflix.
* release_year: Ano que o filme foi lançado.
* rating: Classificação de faixa etária 
* duration: Tempo de duração(temporadas ou minutos).
* listed_in: Gênero do vídeo.
* description: Resumo sobre o que se trata o vídeo.
"""

# Tipos de dados do dataframe
base_netflix.dtypes

# Visualizando tamanho do dataframe
base_netflix.shape

"""* Este dataframe possui no geral 8807 linhas de dados, com  11 colunas do tipo objeto e 1 coluna do tipo int64.

* Esta função nos retornou a quantidade de valores não nulos em cada coluna. Pode se perceber que 6 colunas possuem dados nulos.

Identificando o ano de lançamento do Filme/Tv show mais novo/velho no catálogo da Netflix
"""

#Verificando a data de lançamento mais antiga

min(base_netflix.release_year)

#Verificando a data de lançamento mais atual

max(base_netflix.release_year)

"""Tratando Dados"""

# Verificando valores nulos no dataframe
base_netflix.isnull().sum()

# proporção de nulos coluna director
2634/8807

# proporção de nulos da coluna cast
825/8807

# Dando update nos valores nulos da coluna cast
base_netflix.update(base_netflix['cast'].fillna('Autores Desconhecidos'))

# Dando update nos valores nulos da coluna director
base_netflix.update(base_netflix['director'].fillna('Diretor Desconhecido'))

# Dando update nos valores nulos da coluna country
base_netflix.update(base_netflix['country'].fillna('Região desconhecida'))

# Excluindo linhas com dados faltante da coluna duration, rating e date_added
base_netflix = base_netflix.dropna(subset =['duration'])
base_netflix = base_netflix.dropna(subset =['rating'])
base_netflix = base_netflix.dropna(subset =['date_added'])

"""Podemos observar que as colunas 'cast', 'director' e 'country' contém valores nulos significantes para interferência na análise dos dados. Então substituimos os valores faltantes por 'Autores Desconhecidos', 'Diretor Desconhecido' e 'Região Desconhecida'. E para as colunas 'duration', 'rating' e 'date_added' que contém uma pequena quantidade de valores nulos, decidimos excluir as linhas faltantes."""

# Quantidade de valores únicos por coluna tirando NaN
base_netflix.nunique()

"""Identificando a Proporção de Filmes e TV show(Seriado) que contém na Netflix"""

# Quantidade de Filmes/TV show na Netflix
tipos_quantidade = base_netflix['type'].value_counts(normalize = True)*100
tipos_quantidade

plt.pie(x=tipos_quantidade.values, labels=tipos_quantidade.index,
        autopct='%.2f%%', explode=[.2, 0]) #distância entre as 'fatias' do gráfico
plt.title('Diferença percentual entre os tipos de conteúdos')
plt.show()

"""Verificamos que praticamente 70% dos conteúdos da Netflix são compostos por Filmes e 30% por Tv Show(Seriados).

Identificando o total de Filme/TV show(Seriado) lançado por país
"""

# Total de Filmes/TV show por país
base_netflix['country'] = base_netflix['country'].str.split(', ')
new_base_netflix = base_netflix.explode('country')

"""Identificamos que algumas linhas da coluna 'country' continha mais de um país e decidimos separá-los em linhas diferentes. """

base_netflix.shape

# Total de Filmes/TV show por país
top_countries = pd.crosstab(new_base_netflix["country"], new_base_netflix["type"], margins = True).sort_values(by = 'Movie', ascending = False).head(20)
top_countries

# Gráfico Top 20 países com suas respectivas quantidades de movie e tv show
top_countries.drop(index = 'All', inplace= True)
top_countries[['Movie', 'TV Show']].sort_values(by = 'Movie', ascending = True).plot(kind = 'barh', width=0.8, figsize = (8,10))

"""Como esperado os Estados Unidos é o país dominante na produção de filmes/séries e por isso se encontra no topo do nosso gráfico. 
Por curiosidade a Índia se encontra em segundo lugar de maior produção de filmes/séries que estão na plataforma da Netflix

Identificando a quantidade de conteúdo na Netflix por ano de Lançamento
"""

# Quantidade de conteúdo por ano de lançamento que estão na netflix
ranking_ano_lancamento = base_netflix['release_year'].value_counts().head(10)
ranking_ano_lancamento

plt.figure(figsize=(9, 6))
sns.barplot(x=ranking_ano_lancamento.index, y=ranking_ano_lancamento.values)
plt.xlabel('Ano')
plt.ylabel('Contagem')
plt.title('Proporção da produção por ano')
plt.show()

"""Verificamos que a maior quantidade de conteúdos presentes na Netflix foram lançados no ano de 2018.

Distribuição do mês de lançamento dos filmes / TV Show(Seirado)
"""

#Quebrando as datas, para filtrar o mês
mes = (
    pd.to_datetime(base_netflix['date_added'])
    .dt.month_name() #argumento para pegar o nome do mês
)
mes

"""Como a coluna 'date_added' é do tipo string, precisamos transformá-la em data para manusearmos essa coluna de forma correta. E para sabermos a distribuição do mês de lançamento dos conteúdos, quebramos as datas compostas e filtramos o mês."""

#criando um dataframe concatenando por tipo de conteúdo e coluna mês
tipo_e_mes_add = (
    pd.concat([base_netflix['type'], mes], axis=1)
    .rename(columns={'date_added': 'mes_add'})
    .value_counts()
    .reset_index() #iniciando a contagem a partir do 0
    .rename(columns={0: 'count'}) #renomeando a coluna sem nome para "count"

)
tipo_e_mes_add

#plotando um gráfico com quais tipos (tv show ou movie) é adicionado com mais frequência por mês

plt.figure(figsize=(7, 7))
sns.barplot(data=tipo_e_mes_add, x='mes_add', y='count', hue='type')
plt.xticks(rotation=45)
plt.xlabel('Mes Add')
plt.ylabel('Quantidade')
plt.title('Distribuição de conteúdo adicionado por mês na Netflix')
plt.show()

"""Podemos perceber que tanto os Filmes quanto as Séries são mais adicionados nos meses de Julho e Dezembro por serem meses em que geralmente as pessoas estão de recesso ou férias.

Identificando total de conteúdo por Diretor
"""

diretores = base_netflix['director']
director_count = (
    pd.value_counts(diretores)
    .to_frame(name = "Total Produções")
    .reset_index()
)
director_count.drop(index = 0, inplace= True)
director_count.head(10)

"""Top 10 diretores com produções dentro da plataforma da netflix, sendo Rajiv Chilaka o diretor com maior quantidade de produções.

Distribuição da faixa etária dos Filmes/Tv Show (Seriado)
"""

# Mostrando unicamente as faixas ettárias presentes na coluna rating do dataset
base_netflix['rating'].unique()

# Total de conteúdos pela faixa etária
base_netflix['rating'].value_counts()

"""Verificamos que a maior parte dos conteúdos da netflix são para maiores de 18 anos(TV-MA).
Em segundo temos uma grande quantidade de conteúdos para maiores de 14 anos.
E em terceiro temos os conteúdos livres para qualquer idade.
"""

netflix_filmes=base_netflix[base_netflix['type']=='Movie']

"""Criamos um dataframe só para filmes para separarmos o total desse tipo de conteúdo por faixa etária."""

top_movie = pd.crosstab(base_netflix['rating'], netflix_filmes['type'], margins = True).sort_values(by = 'Movie', ascending = False)
top_movie.drop(index = 'All', columns = 'All', inplace= True)
top_movie

top_movie.plot(kind = 'bar')

netflix_series=base_netflix[base_netflix['type']=='TV Show']

"""Criamos um dataframe só para séries para separarmos o total desse tipo de conteúdo por faixa etária."""

top_serie = pd.crosstab(base_netflix['rating'], netflix_series['type'], margins = True).sort_values(by = 'TV Show', ascending = False)
top_serie.drop(index = 'All', columns = 'All', inplace= True)
top_serie

top_serie.plot(kind = 'bar', color = 'orange')

"""Verificamos que as quantidades de conteúdos por faixa etária são equivalentes para Filmes e Seriados.

Gêneros mais assistidos na Netflix
"""

# Gêneros mais assistidos
base_netflix['listed_in'] = base_netflix['listed_in'].str.split(', ')
new_base_netflix = base_netflix.explode('listed_in')

"""Identificamos que algumas linhas da coluna 'listed_in' continha mais de um gênero de conteúdo e decidimos separá-los em linhas diferentes. """

top_generos = new_base_netflix['listed_in'].value_counts().head(20)
top_generos

# Gráfico de gêneros mais assistidos, TOP 20
top_generos.sort_values(ascending = True).plot(kind = 'barh', width=0.5, figsize = (5,8))

"""Identificando a Média de duração dos Filmes e TV Show(Séries)"""

#Separando os filmes do dataframe, pois como existem TV shows, são medidos por temporadas

netflix_filmes=base_netflix[base_netflix['type']=='Movie']

netflix_filmes['duration']= netflix_filmes['duration'].str.replace(' min','')
netflix_filmes['duration']= netflix_filmes['duration'].astype(str).astype(int)

"""Para contabilizarmos a média em relação aos filmes foi preciso transformar a coluna duração em inteiro para retirar a palavra 'min' e substituir por vazio."""

netflix_filmes['duration'].mean()

"""Observamos que a média de duração dos filmes na Netflix é de 99.58 minutos, aproximadamente 1h e 40 minutos. """

sns.set(style="darkgrid")
sns.kdeplot(data=netflix_filmes['duration'])

#plotando um gráfico com um displot de distribuição normal para os filmes
from scipy import stats 
plt.figure(figsize=(10,5))
sns.distplot(netflix_filmes['duration'], fit = stats.norm, kde=False, color=['green'])
plt.title('Distplot com distribuição normal para os filmes',fontweight="bold")
plt.show()

"""Podemos verificar que uma boa quantidade de filmes na Netflix estão entre 75-120 minutos de duração. Esta coerente, considerando o fato de que não são todas pessoas que conseguem ficar mais de 120 minutos assistindo um filme."""

netflix_tvshow=base_netflix[base_netflix['type']=='TV Show']

netflix_tvshow['duration']= netflix_tvshow['duration'].str.replace(' Seasons','')
netflix_tvshow['duration']= netflix_tvshow['duration'].str.replace(' Season','')
netflix_tvshow['duration']= netflix_tvshow['duration'].astype(str).astype(int)
netflix_tvshow['duration']

"""Para contabilizarmos a média em relação ás séries foi preciso transformar a coluna duração em inteiro para retirar a palavra 'Season' e substituir por vazio."""

netflix_tvshow['duration'].mean()

"""Observamos que a média de temporadas das séries na Netflix é de aproximadamente 2 temporadas. """

sns.set(style="darkgrid")
sns.kdeplot(data=netflix_tvshow['duration'], shade = True)

"""Podemos verificar que a maioria das séries da Netflix contém 2 temporadas, mostrando a preferência por séries curtas e o desinteresse por séries mais longas."""